// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/about': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/about').default>>>>
    }
    '/api/categories': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories').default>>>>
    }
    '/api/projects': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects').default>>>>
    }
    '/api/services': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/services').default>>>>
    }
    '/api/testimonials': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/testimonials').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}